# W O R L D 

/gate/world/geometry/setXLength 60. cm 
/gate/world/geometry/setYLength 60. cm 
/gate/world/geometry/setZLength 60. cm 


/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/setMaterial Air
/gate/scanner/geometry/setXLength 55. cm
/gate/scanner/geometry/setYLength 55. cm
/gate/scanner/geometry/setZLength 55. cm
/gate/scanner/vis/forceWireframe

/gate/scanner/daughters/name dummyAir
/gate/scanner/daughters/insert box
/gate/dummyAir/setMaterial Air
/gate/dummyAir/geometry/setXLength 55. cm
/gate/dummyAir/geometry/setYLength 55. cm
/gate/dummyAir/geometry/setZLength 55. cm
/gate/dummyAir/vis/forceWireframe

# PHANTOM planar
# Plastic
#/gate/dummyAir/daughters/name phantom
#/gate/dummyAir/daughters/insert box
#/gate/phantom/setMaterial PMMA
#/gate/phantom/geometry/setXLength 160. mm
#/gate/phantom/geometry/setYLength 180. mm
#/gate/phantom/geometry/setZLength 13.5 mm
#/gate/phantom/vis/setColor cyan
#/gate/phantom/vis/forceWireframe
# Water with fdg
#/gate/phantom/daughters/name fdgvolume
#/gate/phantom/daughters/insert box
#/gate/fdgvolume/setMaterial Water
#/gate/fdgvolume/geometry/setXLength 160. mm
#/gate/fdgvolume/geometry/setYLength 180. mm
#/gate/fdgvolume/geometry/setZLength 3.5 mm
#/gate/fdgvolume/vis/setColor red
#/gate/fdgvolume/vis/forceWireframe

# PHANTOM cylinder 
# Plastic
/gate/dummyAir/daughters/name phantom
/gate/dummyAir/daughters/insert cylinder
/gate/phantom/setMaterial PMMA
#/gate/phantom/geometry/setRmin 22.5 mm
/gate/phantom/geometry/setRmax 32.5 mm
/gate/phantom/geometry/setHeight 200. mm
#/gate/phantom/geometry/setZLength 13.5 mm
/gate/phantom/placement/setRotationAxis 1 0 0 
/gate/phantom/placement/setRotationAngle 90 deg 
#/gate/phantom/placement/setRotationAxis 0 1 0 
#/gate/phantom/placement/setRotationAngle 90 deg
/gate/phantom/vis/setColor cyan
/gate/phantom/vis/forceWireframe
# Water with fdg
/gate/phantom/daughters/name fdgvolume
/gate/phantom/daughters/insert cylinder
/gate/fdgvolume/setMaterial Water
/gate/fdgvolume/geometry/setRmax 22.5 mm
/gate/fdgvolume/geometry/setHeight 180. mm
#/gate/fdgvolume/geometry/setZLength 3.5 mm
/gate/fdgvolume/vis/setColor red
/gate/fdgvolume/vis/forceWireframe


# DETECTOR HEAD
/gate/dummyAir/daughters/name detectorhead
/gate/dummyAir/daughters/insert box
/gate/detectorhead/setMaterial BaSO4
/gate/detectorhead/geometry/setXLength 160. mm
/gate/detectorhead/geometry/setYLength 180. mm
/gate/detectorhead/geometry/setZLength 20. mm
/gate/detectorhead/vis/setColor green
/gate/detectorhead/repeaters/insert linear
/gate/detectorhead/linear/setRepeatNumber 2
/gate/detectorhead/linear/setRepeatVector 0. 0. 229. mm
/gate/detectorhead/vis/forceWireframe


# MODULE
/gate/detectorhead/daughters/name module
/gate/detectorhead/daughters/insert box
/gate/module/setMaterial BaSO4
/gate/module/geometry/setXLength 13. mm
/gate/module/geometry/setYLength 44.5 mm
/gate/module/geometry/setZLength 20. mm
/gate/module/vis/setColor red
/gate/module/repeaters/insert cubicArray
/gate/module/cubicArray/setRepeatNumberX 12
/gate/module/cubicArray/setRepeatNumberY 4
/gate/module/cubicArray/setRepeatNumberZ 1
/gate/module/cubicArray/setRepeatVector 13. 44.5 0 mm
/gate/module/vis/forceWireframe


# SUBMODULE
/gate/module/daughters/name submodule
/gate/module/daughters/insert box
/gate/submodule/setMaterial PTFE
/gate/submodule/geometry/setXLength 4.6 mm
/gate/submodule/geometry/setYLength 18.4 mm
/gate/submodule/geometry/setZLength 20. mm
/gate/submodule/vis/setColor green
/gate/submodule/repeaters/insert cubicArray
/gate/submodule/cubicArray/setRepeatNumberX 2
/gate/submodule/cubicArray/setRepeatNumberY 2
/gate/submodule/cubicArray/setRepeatNumberZ 1
/gate/submodule/cubicArray/setRepeatVector 4.9 21.9 0 mm
/gate/submodule/vis/forceWireframe


# CRYSTAL
/gate/submodule/daughters/name crystal
/gate/submodule/daughters/insert box
/gate/crystal/geometry/setXLength 2. mm
/gate/crystal/geometry/setYLength 2. mm
/gate/crystal/geometry/setZLength 20. mm
/gate/crystal/setMaterial LYSO
/gate/crystal/vis/setColor yellow
/gate/crystal/vis/forceWireframe

# REPEAT CRYSTAL
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 2
/gate/crystal/cubicArray/setRepeatNumberY 8
/gate/crystal/cubicArray/setRepeatNumberZ 1
/gate/crystal/cubicArray/setRepeatVector 2.3 2.3 0 mm


# ATTACH VOLUMES TO SYSTEM 
/gate/systems/scanner/level1/attach detectorhead
/gate/systems/scanner/level2/attach module
/gate/systems/scanner/level3/attach submodule
/gate/systems/scanner/level4/attach crystal

# ATTACH SENSITIVE DETECTOR
/gate/crystal/attachCrystalSD

# PHANTOM defined as SENSITIVE 
/gate/dummyAir/attachPhantomSD 
/gate/phantom/attachPhantomSD 
/gate/fdgvolume/attachPhantomSD 
/gate/module/attachPhantomSD 
/gate/submodule/attachPhantomSD 











